baseURL = "https://kirklingtonhowgrave.org/" # Update to your Netlify URL or custom domain
languageCode = "en-us"
title = "Kirklington & Sutton Howgrave"
theme = "ananke"
[services]
  [services.googleAnalytics]
    googleAnalytics = "G-H88K87FTSQ"