baseURL = "https://teal-profiterole-6b63ec.netlify.app/" # Update to your Netlify URL or custom domain
languageCode = "en-us"
title = "Village Parish"
theme = "ananke"
[params]
  site_logo = "/images/logo.png"
